images: Python 3.5.4 x86

environment:
    matrix:
        - TOXENV: py27
        - TOXENV: py35
        - TOXENV: py36
        - TOXENV: py37

platform:
    - x86
build_script:
    python .\python_client\runner.py