environment:
    matrix:
        - PYTHON: "C:\\Python27"
        - PYTHON: "C:\\Python33"
        - PYTHON: "C:\\Python34"
        - PYTHON: "C:\\Python35"
platform:
    - x86
build_script:
    python -m pip install Flask==1.1.2
    python -m pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip

